// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Nosotras documents
 */
interface AboutDocumentData {
  /**
   * Título field in *Nosotras*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Texto field in *Nosotras*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Nosotras document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<AboutDocumentData>, "about", Lang>;

/**
 * Content for Happening documents
 */
interface HappeningDocumentData {
  /**
   * Título field in *Happening*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: happening.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Imagen field in *Happening*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: happening.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Categoria field in *Happening*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: happening.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  category: prismic.SelectField<
    "Arte" | "Cultura" | "Música" | "Gastronomía" | "Cine"
  >;

  /**
   * Fecha del evento field in *Happening*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: happening.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * Fecha de finalización (opcional) field in *Happening*
   *
   * - **Field Type**: Date
   * - **Placeholder**: Si el evento tiene múltiples días
   * - **API ID Path**: happening.end_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  end_date: prismic.DateField;

  /**
   * Horario (opcional) field in *Happening*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: 12:00hrs
   * - **API ID Path**: happening.time
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  time: prismic.RichTextField;

  /**
   * Descripción field in *Happening*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: happening.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Nombre de Locación  field in *Happening*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: happening.location_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  location_name: prismic.KeyTextField;

  /**
   * URL de Locación field in *Happening*
   *
   * - **Field Type**: Link
   * - **Placeholder**: https://...
   * - **API ID Path**: happening.location_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  location_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Costo (opcional) field in *Happening*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: $130 pesos
   * - **API ID Path**: happening.cost
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cost: prismic.RichTextField;
}

/**
 * Happening document from Prismic
 *
 * - **API ID**: `happening`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HappeningDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HappeningDocumentData>,
    "happening",
    Lang
  >;

/**
 * Content for Lugar documents
 */
interface LugarDocumentData {
  /**
   * Nombre field in *Lugar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lugar.nombre
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nombre: prismic.KeyTextField;

  /**
   * Área de la ciudad field in *Lugar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Centro de monterrey
   * - **API ID Path**: lugar.area
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  area: prismic.KeyTextField;

  /**
   * Categoria field in *Lugar*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Categoría
   * - **API ID Path**: lugar.categoria
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  categoria: prismic.SelectField<
    | "Bares & Cantinas"
    | "Monumentos Históricos"
    | "Cafeterías"
    | "Música en Vivo"
    | "Espacios de Arte"
    | "Restaurantes"
    | "Parques"
  >;

  /**
   * Link field in *Lugar*
   *
   * - **Field Type**: Link
   * - **Placeholder**: https://...
   * - **API ID Path**: lugar.link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Link de mapa field in *Lugar*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Google maps url
   * - **API ID Path**: lugar.mapLink
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  mapLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Link de cápsula field in *Lugar*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: lugar.capsuleLink
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  capsuleLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Lugar document from Prismic
 *
 * - **API ID**: `lugar`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LugarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<LugarDocumentData>, "lugar", Lang>;

/**
 * Content for Post documents
 */
interface PostDocumentData {
  /**
   * Portada field in *Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: post.hero
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hero: prismic.ImageField<never>;

  /**
   * Titulo (H1) field in *Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: post.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Título SEO field in *Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: post.seo_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_title: prismic.KeyTextField;

  /**
   * Descripción SEO field in *Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: post.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Fecha de publicación field in *Post*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: post.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * Autor (opcional) field in *Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: post.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author: prismic.KeyTextField;

  /**
   * Cuerpo de texto field in *Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: post.body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Post document from Prismic
 *
 * - **API ID**: `post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PostDocumentData>, "post", Lang>;

/**
 * Content for Ruta documents
 */
interface RouteDocumentData {
  /**
   * Título field in *Ruta*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: route.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Imagen field in *Ruta*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: route.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Categoria field in *Ruta*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: route.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  category: prismic.SelectField<"En la ciudad" | "Fuera de la ciudad">;

  /**
   * Descripción field in *Ruta*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: route.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Ruta document from Prismic
 *
 * - **API ID**: `route`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RouteDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<RouteDocumentData>, "route", Lang>;

export type AllDocumentTypes =
  | AboutDocument
  | HappeningDocument
  | LugarDocument
  | PostDocument
  | RouteDocument;

/**
 * Default variation for Image Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Image*
 */
type ImageSliceVariation = ImageSliceDefault;

/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSlice = prismic.SharedSlice<"image", ImageSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      HappeningDocument,
      HappeningDocumentData,
      LugarDocument,
      LugarDocumentData,
      PostDocument,
      PostDocumentData,
      RouteDocument,
      RouteDocumentData,
      AllDocumentTypes,
      ImageSlice,
      ImageSliceVariation,
      ImageSliceDefault,
    };
  }
}
