// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Happening documents
 */
interface HappeningDocumentData {
  /**
   * Title field in *Happening*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: happening.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Image field in *Happening*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: happening.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Category field in *Happening*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: happening.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  category: prismic.SelectField<"Arte" | "Cultura" | "Música" | "Gastronomía">;

  /**
   * Date field in *Happening*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: happening.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * Description field in *Happening*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: happening.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Location name field in *Happening*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: happening.location_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  location_name: prismic.KeyTextField;

  /**
   * Location url field in *Happening*
   *
   * - **Field Type**: Link
   * - **Placeholder**: https://...
   * - **API ID Path**: happening.location_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  location_url: prismic.LinkField;
}

/**
 * Happening document from Prismic
 *
 * - **API ID**: `happening`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HappeningDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HappeningDocumentData>,
    "happening",
    Lang
  >;

/**
 * Content for Lugar documents
 */
interface LugarDocumentData {
  /**
   * Nombre field in *Lugar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lugar.nombre
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nombre: prismic.KeyTextField;

  /**
   * Treasure Hunt field in *Lugar*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: lugar.treasure_hunt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  treasure_hunt: prismic.BooleanField;

  /**
   * Categoria field in *Lugar*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Categoría
   * - **API ID Path**: lugar.categoria
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  categoria: prismic.SelectField<
    | "Bares & Cantinas"
    | "Monumentos Históricos "
    | "Cafeterías"
    | "Música en vivo"
    | "Espacios de Arte"
    | "Restaurantes"
  >;
}

/**
 * Lugar document from Prismic
 *
 * - **API ID**: `lugar`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LugarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<LugarDocumentData>, "lugar", Lang>;

export type AllDocumentTypes = HappeningDocument | LugarDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HappeningDocument,
      HappeningDocumentData,
      LugarDocument,
      LugarDocumentData,
      AllDocumentTypes,
    };
  }
}
