/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,ts,jsx,tsx}"],
  future: {
    hoverOnlyWhenSupported: true
  },
  theme: {
    extend: {
      animation: {
        fadeIn: 'fadeIn 600ms cubic-bezier(0.39, 0.575, 0.565, 1) forwards',
        fadeIn2: 'fadeIn2 800ms cubic-bezier(0.39, 0.575, 0.565, 1) forwards',
        fadeIn3: 'fadeIn3 900ms cubic-bezier(0.39, 0.575, 0.565, 1) forwards',
        fadeIn4: 'fadeIn4 1100ms cubic-bezier(0.39, 0.575, 0.565, 1) forwards',
        fadeSimple: 'fadeSimple 600ms cubic-bezier(0.39, 0.575, 0.565, 1) forwards',

      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(6px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn2: {
          '0%, 25%': { opacity: '0', transform: 'translateY(6px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn3: {
          '0%, 40%': { opacity: '0', transform: 'translateY(6px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn4: {
          '0%, 65%': { opacity: '0', transform: 'translateY(6px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeSimple: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
      },
      screens: {
        'xsm': '460px',
        'sm': '640px',
        'md': '768px',
        'md-lg': '875px',
        'lg': '1024px',
        'xl': '1280px',
        '2xl': '1650px',
      },
      colors: {
        fern: "#00808B",
        indagaBlue: "#00808B",
        indagaBrown: "#956D4C",
        offwhite: "#F4F5F4",
        ocre: "#DA7829",
        blue: "#465FC0",
        eerie: "#212322", 
        mindaro: "#CAE47C",
        guiaOrange: "#FF7434",
        guiaCyan: "#72DFFC",
        guiaMustard: "#F3BB44",
        guiaPurple: "#755EFA",
        guiaSunset: "#FF5542",
        guiaPink:"#FF60B8"
      },
    },
    fontWeight: {
      normal: '358',
      medium: '448',
    },
  },
  plugins: [],
  safelist: [
    'text-guiaOrange',
    'text-fern',
    'group-hover:text-fern',
    'hover:text-guiaOrange',
    'active:text-guiaOrange',
    'hover:fill-guiaOrange',
    'bg-guiaOrange',
    'text-guiaPurple',
    'hover:text-guiaPurple',
    'active:text-guiaPurple',
    'hover:fill-guiaPurple',
    'bg-guiaPurple',
    'text-guiaMustard',
    'hover:text-guiaMustard',
    'active:text-guiaMustard',
    'hover:fill-guiaMustard',
    'bg-guiaMustard',
    'text-guiaCyan',
    'hover:text-guiaCyan',
    'active:text-guiaCyan',
    'hover:fill-guiaCyan',
    'bg-guiaCyan',
    'text-guiaSunset',
    'hover:text-guiaSunset',
    'active:text-guiaSunset',
    'hover:fill-guiaSunset',
    'bg-guiaSunset',
    'text-guiaPink',
    'hover:text-guiaPink',
    'active:text-guiaPink',
    'hover:fill-guiaPink',
    'bg-guiaPink',
  ],
};
